language: python

install:
  - sudo apt-get update
  # Install the dependencies and the package:
  - pip install -r requirements.txt
  - python setup.py install
  # Now get set up to run jupyter notebooks:
  - sudo apt-get install texlive-latex-recommended
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install chktex
  - sudo apt-get install dvipng
  - pip install --upgrade jupyter
  - pip install nbconvert

script:
  # Run the unit tests:
  # - nosetests
  # Run the demo notebook:
  - jupyter nbconvert --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=600 --to notebook --execute docs/notebooks/demo.ipynb
